name: selling_pictures_platform
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  flutter_sidekick: ^0.1.3
  arkit_plugin: ^1.0.1
  transparent_image: ^2.0.0
  cupertino_icons: ^1.0.3
  cloud_firestore: ^2.3.0
  firebase_auth: ^2.0.0
  shared_preferences: ^2.0.5
  fluttertoast: ^8.0.6
  image_picker: ^0.8.0+3
  firebase_storage: ^9.0.0
  flutter_staggered_grid_view: ^0.4.0
  provider: ^5.0.0
  universal_platform: ^1.0.0+1
  path_provider: ^2.0.1
  image: ^3.0.2
  intl: ^0.17.0
  font_awesome_flutter: ^9.0.0
  flutter_neumorphic: ^3.1.0
  page_transition: ^2.0.2
  google_fonts: ^2.1.0
  like_button: ^2.0.2
  stripe_payment: ^1.1.0
  stripe_sdk: ^5.0.0-nullsafety.0
  url_launcher: ^6.0.3
  carousel_slider: ^4.0.0
  flutter_email_sender: ^5.0.0
  flutter_gradient_colors: ^1.0.0
  flutter_credit_card: ^2.0.0
  google_mobile_ads: ^0.13.0
  gsheets: ^0.3.1
  sliding_up_panel: ^2.0.0+1
  flutter_rating_bar: ^4.0.0
  dropdown_date_picker: ^0.1.1+2
  grouped_buttons: ^1.0.4
  import_sorter: ^4.6.0
  simple_animations: ^3.1.1
  flutter_brand_palettes: ^0.3.8




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  image_path: "icon/leewayIcon.png"
  android: true
  ios: true

flutter:

  uses-material-design: true
  fonts:
    - family: karakaze-R
      fonts:
        - asset: assets/fonts/karakaze-R.ttf

  assets:
     - images/welcome.png
     - images/login.png
     - images/admin.png
     - images/cash.png
     - images/painter1.png
     - images/painter2.png
     - images/painter3.png
     - images/painter4.png
     - images/painter5.png
     - images/LEEWAY_SAMPLE.png
     - images/home_image.png
     - images/handshake.png
     - images/CashPayment-pana.png
     - images/Photos-bro.png
     - images/Makingart-bro.png
     - images/Images-bro.png
     - images/Listing.png
     - images/Revenue-cuate.png
     - images/Delivery-rafiki.png
     - images/Delivery-amico.png
     - images/Online_Groceries-rafiki.png
     - images/Credit_card-cuate.png
     - images/Credit-card-pana.png
     - images/isColor_Horizontal.png
     - images/isColor_Vertical.png
     - images/NoColor_horizontal.png
     - images/NoColor_Vertical.png
     - images/white.png