name: selling_pictures_platform
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  arkit_plugin: ^1.0.1
  cupertino_icons: ^0.1.2
  cloud_firestore: ^1.0.6
  firebase_auth: ^1.4.1
  shared_preferences: ^2.0.5
  fluttertoast: ^8.0.6
  image_picker: ^0.8.0+3
  firebase_storage: ^8.1.3
  flutter_staggered_grid_view: ^0.4.0
  provider: ^5.0.0
  path_provider: ^2.0.1
  image: ^3.0.2
  intl: ^0.17.0
  font_awesome_flutter: ^9.0.0
  flutter_neumorphic: ^3.1.0
  page_transition: ^2.0.2
  google_fonts: ^2.1.0
  like_button: ^2.0.2
  stripe_payment: ^1.1.0
  stripe_sdk: ^5.0.0-nullsafety.0
  url_launcher: ^6.0.3
  carousel_slider: ^3.0.0

  flutter_email_sender: ^5.0.0
  flutter_gradient_colors: ^1.0.0
  flutter_credit_card: ^2.0.0
  google_mobile_ads: ^0.13.0
  gsheets: ^0.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  fonts:
    - family: karakaze-R
      fonts:
        - asset: assets/fonts/karakaze-R.ttf
#    - family: Signatra
#      fonts:
#        - asset: assets/fonts/Signatra.ttf

  assets:
     - images/welcome.png
     - images/login.png
     - images/admin.png
     - images/cash.png
     - images/painter1.png
     - images/painter2.png
     - images/painter3.png
     - images/painter4.png
     - images/painter5.png
     - images/LEEWAY_SAMPLE.png
     - images/home_image.png
     - images/handshake.png
     - images/CashPayment-pana.png
     - images/Photos-bro.png
     - images/Makingart-bro.png
     - images/Images-bro.png
     - images/Listing.png
     - images/Revenue-cuate.png
     - images/Delivery-rafiki.png
     - images/Delivery-amico.png
     - images/Online_Groceries-rafiki.png
     - images/Credit_card-cuate.png
     - images/Credit-card-pana.png