name: selling_pictures_platform
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  cloud_firestore: ^1.0.6
  firebase_auth: ^1.1.1
  shared_preferences: ^2.0.5
  fluttertoast: ^8.0.6
  image_picker: ^0.7.4
  firebase_storage: ^8.0.4
  flutter_staggered_grid_view: ^0.4.0
  provider: ^5.0.0
  path_provider: ^2.0.1
  image: ^3.0.2
  intl: ^0.17.0
  font_awesome_flutter: ^9.0.0
  flutter_neumorphic: ^3.1.0
  page_transition: ^2.0.2
  google_fonts: ^2.1.0
  like_button: ^2.0.2
  stripe_payment: ^1.1.0
  stripe_sdk: ^5.0.0-nullsafety.0
  url_launcher: ^6.0.3
  carousel_slider: ^3.0.0
  arkit_plugin: ^0.6.2
  flutter_email_sender: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
  assets:
     - images/welcome.png
     - images/login.png
     - images/admin.png
     - images/cash.png
     - images/painter1.png
     - images/painter2.png
     - images/painter3.png
     - images/painter4.png
     - images/painter5.png
     - images/LEEWAY_SAMPLE.png